### PR TITLE
Improve thumbnail preview in the video editor

### PR DESCRIPTION
**Pull request by staubesv**
Hi @krinnewitz 

Here comes a first PR for the thumbnail tab

- Use 16:9 aspect ratio (320x180px) for thumbnail preview in video editor
- Use dedicated encoding profiles for the thumbnail preview images for the video editor

### CODE REVIEW

**Comment by krinnewitz** [comment]
Hi @staubesv 

Thanks for the PR. I think the encoding profile used for default thumbnail creation in fast.xml should be changed as well. What do you think?

**Comment by staubesv** [comment]
Oops... forgot about that ;-)

**Comment by staubesv** [comment]
Hi @krinnewitz I've updated the PR which now also includes the re-designed thumbnail tab (and uses the correct encoding profile in fast.xml).

Note that I could solve the problems discussed today: The keyword "block element" triggered some memories (layout problems) and using onclick instead of ng-click solved the connection to the input field (for whatever reason).

**Comment by krinnewitz** [comment]
Thanks @staubesv 

I merged it and did some fixes on top.

**Pull request merged**
